In [3]:
import numpy as np

In [4]:
X=np.load("X_data.npy")
Y=np.load("Y_data.npy")

In [5]:
X.shape ,Y.shape

((500, 2), (500,))

In [6]:
def distance(p1,p2):
    

In [10]:
def predict(val,k=5):
    pt=np.array(val)
    a=(X-pt)**2
    dis=(a[:][:,0]+a[:][:,1])**0.5
    idx=dis.argsort()[:k]
    y_val=Y[idx]
    clas,fre=np.unique(y_val,return_counts=True)
    print("class=",clas[fre.argmax()],"accuracy=",max(fre)/k)
       

In [12]:
predict((0,10))
#print(ar)

class= 1 accuracy= 1.0


In [63]:
te=ar.argsort()

In [64]:
te[:5]

array([8, 2, 9, 7, 4], dtype=int32)

In [23]:
tes=X[0:5]
print(tes)
pt=np.array([1,0])

[[-3.54122245  3.10356106]
 [ 3.03469932  1.02382996]
 [ 2.09934302  3.11614107]
 [ 6.04308149  2.39113609]
 [ 3.5292764   2.35276246]]


In [51]:
a=(tes-pt)**2
b=(a[:][:,0]+a[:][:,1])**0.5

In [52]:
print(b)

[5.50043567 2.27776845 3.30437441 5.58123666 3.45437842]


In [5]:
arr=np.array([1,3,4,5,6,7,4,3,2,7,8])

In [10]:
l,g=np.unique(arr,return_counts=True)
print(l,g)

[1 2 3 4 5 6 7 8] [1 1 2 2 1 1 2 1]


In [9]:
l[g.argmax()]

3

In [14]:
import matplotlib.pyplot as plt

In [34]:
print(a)

[[20.6227013   9.63209125]
 [ 4.14000133  1.04822779]
 [ 1.20855507  9.71033515]
 [25.4326709   5.71753178]
 [ 6.39723908  5.5354912 ]]


In [3]:
np.unique(return_counts=True)

Signature:
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
)
Docstring:
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
return_counts : bool, optiona